export const calendarStyles = {
  root: 'w-full flex flex-col items-center',
  months: 'w-full space-y-4',
  month: 'space-y-4',
  caption: 'flex justify-center pt-1 relative items-center',
  caption_label: 'text-sm font-medium text-gray-700',
  nav: 'flex items-center space-x-1',
  nav_button: 'p-1 rounded-md hover:bg-gray-100 transition-colors',
  table: 'w-full border-collapse',
  head_row: 'flex justify-center',
  head_cell: 'w-9 text-xs font-medium text-gray-500 py-2',
  row: 'flex justify-center mt-1',
  cell: 'relative p-0 text-center',
  day: [
    'h-9 w-9 p-0 font-normal',
    'flex items-center justify-center',
    'hover:bg-gray-100 rounded-md transition-colors',
    'cursor-pointer select-none',
  ].join(' '),
  day_selected: [
    'bg-blue-600 text-white',
    'hover:bg-blue-700',
    'focus:bg-blue-700 focus:text-white',
    'rounded-md',
  ].join(' '),
  day_today: 'bg-gray-100 font-semibold',
  day_outside: 'text-gray-400',
  day_disabled: 'text-gray-300 cursor-not-allowed',
  day_hidden: 'invisible',
}
